name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    - name: Install dependencies (C#)
      run: dotnet tool install -g dotnet-format && echo ::add-path::$HOME/.dotnet/tools
    - name: format
      run: dotnet-format --check
    - name: test
      run: dotnet test -v n
